### ISSUE TITLE
Missing end body and html tags

### ISSUE THREAD

**Issue by nvx** [aerohub/hugo-simpledoc-theme#2]
The generated html appears to be missing the end body and html tags. From a quick look I believe it's because layouts/index.html is missing `</body></html>` at the end, although I am a complete novice with hugo so I'm not sure if this is the proper place that this should be added.

As an aside, it appears that the missing body end tag breaks also live reload.

**Comment by aerohub** [comment]
@nvx You are right! Thank you much for the issue. I have updated the the layout
